MFEM_DIR ?= $(APPLICATION_DIR)/../mfem/installed

include $(MFEM_DIR)/share/mfem/config.mk

ADDITIONAL_INCLUDES += $(MFEM_INCFLAGS)
ADDITIONAL_LIBS     += $(MFEM_LIBS) -lmfem-common

$(info ADDITIONAL_INCLUDES = $(ADDITIONAL_INCLUDES));
$(info ADDITIONAL_LIBS     = $(ADDITIONAL_LIBS));
