name: BuildTest
on:
  push:
    branches:
       - master
  pull_request:

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: BuildTestUbuntu
    env:
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v2
      # Now build in a container with all deps
      - name: PrintGithubContext
        run: echo $PRCOMMITSHA
      - name: DockerBuildTestPR
        if:  ${{ github.event.pull_request.head.sha != '' }}
        run: docker build -t ci-hephaestus-ubuntu --build-arg build_git_sha=$PRCOMMITSHA docker/hephaestus
      - name:  DockerBuildTestPush
        if:  ${{ github.event.pull_request.head.sha == '' }}
        run: docker build -t ci-hephaestus-ubuntu --build-arg build_git_sha=$GITHUB_SHA docker/hephaestus
